import sys

with open('supabase/migrations/047_publish_audit.sql', 'r', encoding='utf-8') as f:
    lines = f.readlines()

for i, line in enumerate(lines):
    if "v_html :=" in line and "Hello" in line:
        lines[i] = "        v_html := '<!DOCTYPE html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>KGAC Audit Assignment</title><style>body { font-family: -apple-system, BlinkMacSystemFont, ''Segoe UI'', Roboto, Helvetica, Arial, sans-serif; background-color: #f8fafc; margin: 0; padding: 0; } .container { max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05); border: 1px solid #e2e8f0; } .header { background-color: #0f172a; padding: 30px 40px; text-align: center; } .header h1 { color: #ffffff; margin: 0; font-size: 24px; font-weight: 600; letter-spacing: -0.5px; } .content { padding: 40px; color: #334155; line-height: 1.6; } .content h2 { color: #0f172a; font-size: 20px; margin-top: 0; } .credentials-box { background-color: #f1f5f9; border-left: 4px solid #3b82f6; padding: 20px; margin: 25px 0; border-radius: 0 6px 6px 0; } .cred-row { margin-bottom: 12px; } .cred-label { font-weight: 600; color: #475569; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; display: block; margin-bottom: 4px; } .cred-value { font-size: 16px; color: #0f172a; font-weight: 600; display: block; } .footer { padding: 20px 40px; background-color: #f8fafc; border-top: 1px solid #e2e8f0; text-align: center; color: #64748b; font-size: 13px; }</style></head><body><div class=\"container\"><div class=\"header\"><h1>KGAC Audit Allocation</h1></div><div class=\"content\"><h2>Audit Assignment Details</h2><p>Hello ' || v_resource_name || ',</p><p>You have been scheduled for an upcoming audit assignment. Please review the details below:</p><div class=\"credentials-box\"><div class=\"cred-row\"><span class=\"cred-label\">Project / Client</span><span class=\"cred-value\">' || v_project_name || '</span></div><div class=\"cred-row\"><span class=\"cred-label\">Date</span><span class=\"cred-value\">' || v_audit_date || '</span></div><div class=\"cred-row\"><span class=\"cred-label\">Assigned Role</span><span class=\"cred-value\" style=\"text-transform: capitalize;\">' || v_member.role || '</span></div><div class=\"cred-row\" style=\"margin-bottom: 0;\"><span class=\"cred-label\">Contact Person</span><span class=\"cred-value\">' || COALESCE(v_contact_person, 'Project Manager') || '</span></div></div><p>If you have any questions or conflicts regarding this schedule, please contact the project manager immediately.</p></div><div class=\"footer\">This is an automated message from Kumar Aggarwal Gaurav and Co.<br>Please do not reply directly to this email.</div></div></body></html>';\n"
        
with open('supabase/migrations/047_publish_audit.sql', 'w', encoding='utf-8') as f:
    f.writelines(lines)
